<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShapeEngine.Avalonia\ShapeEngine.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DaveGreen.ShapeEngine" Version="5.3.0" />
    <PackageReference Include="Avalonia.Markup.Declarative" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
  </ItemGroup>

</Project>
